In [22]:
import pandas as pd
ventas= pd.read_csv(
    "../data/ventas.csv",
    dtype={"precio_unitario": "float64"}
)

In [4]:
ventas.head(10)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.1
5,2024-01-03,Oeste,Javier Sanz,Escritorio,Mobiliario,2,450,0.0
6,2024-01-03,Norte,Carlos Vega,Silla Ergo,Mobiliario,4,280,0.0
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280,0.0
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.1
9,2024-01-03,Centro,Pedro Diaz,Escritorio,Mobiliario,2,450,0.0

In [6]:
mascara = ventas["region"] =="Sur"
ventas_sur = ventas[mascara]
ventas_sur.tail()

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1156,2024-12-17,Sur,Luis Gomez,Teclado Mec,Accesorios,11,95,0.15
1163,2024-12-19,Sur,Luis Gomez,Silla Ergo,Mobiliario,2,280,0.00
1181,2024-12-25,Sur,Ana Torres,Tablet Air,Tecnologia,14,640,0.00
1191,2024-12-30,Sur,Luis Gomez,Silla Ergo,Mobiliario,3,280,0.00
1192,2024-12-30,Sur,Javier Sanz,Teclado Mec,Accesorios,8,95,0.10

In [7]:
ventas[ventas["region"] == "Sur"]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.00
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.10
14,2024-01-05,Sur,Pedro Diaz,Teclado Mec,Accesorios,12,95,0.05
21,2024-01-07,Sur,Marta Ruiz,Auriculares,Accesorios,4,130,0.10
22,2024-01-08,Sur,Elena Mora,Teclado Mec,Accesorios,3,95,0.00
...,...,...,...,...,...,...,...,...
1156,2024-12-17,Sur,Luis Gomez,Teclado Mec,Accesorios,11,95,0.15
1163,2024-12-19,Sur,Luis Gomez,Silla Ergo,Mobiliario,2,280,0.00
1181,2024-12-25,Sur,Ana Torres,Tablet Air,Tecnologia,14,640,0.00
1191,2024-12-30,Sur,Luis Gomez,Silla Ergo,Mobiliario,3,280,0.00
1192,2024-12-30,Sur,Javier Sanz,Teclado Mec,Accesorios,8,95,0.10

In [12]:
df_filtrado=ventas[ (ventas["region"] == "Sur") & (ventas["precio_unitario"] > 90) ]
df_filtrado

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.00
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.10
14,2024-01-05,Sur,Pedro Diaz,Teclado Mec,Accesorios,12,95,0.05
21,2024-01-07,Sur,Marta Ruiz,Auriculares,Accesorios,4,130,0.10
22,2024-01-08,Sur,Elena Mora,Teclado Mec,Accesorios,3,95,0.00
...,...,...,...,...,...,...,...,...
1156,2024-12-17,Sur,Luis Gomez,Teclado Mec,Accesorios,11,95,0.15
1163,2024-12-19,Sur,Luis Gomez,Silla Ergo,Mobiliario,2,280,0.00
1181,2024-12-25,Sur,Ana Torres,Tablet Air,Tecnologia,14,640,0.00
1191,2024-12-30,Sur,Luis Gomez,Silla Ergo,Mobiliario,3,280,0.00
1192,2024-12-30,Sur,Javier Sanz,Teclado Mec,Accesorios,8,95,0.10

In [18]:
df_filtrado = ventas[ (ventas["region"] == "Sur") | (ventas["region"] == "Norte")]
df_filtrado

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.1
6,2024-01-03,Norte,Carlos Vega,Silla Ergo,Mobiliario,4,280,0.0
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280,0.0
10,2024-01-04,Norte,Sofia Leon,Monitor 27,Tecnologia,3,320,0.1
...,...,...,...,...,...,...,...,...
1191,2024-12-30,Sur,Luis Gomez,Silla Ergo,Mobiliario,3,280,0.0
1192,2024-12-30,Sur,Javier Sanz,Teclado Mec,Accesorios,8,95,0.1
1194,2024-12-30,Norte,Ana Torres,Tablet Air,Tecnologia,4,640,0.0
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.0
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45,0.0

In [20]:
ventas [ ventas["unidades"] == 1]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280,0.00
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.10
17,2024-01-06,Oeste,Marta Ruiz,Laptop Pro,Tecnologia,1,1200,0.00
26,2024-01-09,Centro,Sofia Leon,Teclado Mec,Accesorios,1,95,0.00
...,...,...,...,...,...,...,...,...
1126,2024-12-08,Sur,Pedro Diaz,Escritorio,Mobiliario,1,450,0.00
1137,2024-12-12,Norte,Pedro Diaz,Teclado Mec,Accesorios,1,95,0.00
1146,2024-12-15,Norte,Pedro Diaz,Laptop Pro,Tecnologia,1,1200,0.00
1164,2024-12-20,Norte,Javier Sanz,Escritorio,Mobiliario,1,450,0.15
1190,2024-12-29,Centro,Luis Gomez,Laptop Pro,Tecnologia,1,1200,0.10

In [19]:
df_filtrado["region"].unique()

<StringArray>
['Sur', 'Norte']
Length: 2, dtype: str

In [16]:
sorted(df_filtrado["precio_unitario"].unique())

[np.int64(95),
 np.int64(130),
 np.int64(280),
 np.int64(320),
 np.int64(450),
 np.int64(640),
 np.int64(1200)]

In [23]:
ventas[ ventas["region"].isin(["Sur", "Norte"])]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320.0,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130.0,0.1
6,2024-01-03,Norte,Carlos Vega,Silla Ergo,Mobiliario,4,280.0,0.0
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280.0,0.0
10,2024-01-04,Norte,Sofia Leon,Monitor 27,Tecnologia,3,320.0,0.1
...,...,...,...,...,...,...,...,...
1191,2024-12-30,Sur,Luis Gomez,Silla Ergo,Mobiliario,3,280.0,0.0
1192,2024-12-30,Sur,Javier Sanz,Teclado Mec,Accesorios,8,95.0,0.1
1194,2024-12-30,Norte,Ana Torres,Tablet Air,Tecnologia,4,640.0,0.0
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320.0,0.0
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45.0,0.0

In [25]:
df_filtrado = ventas[ventas["precio_unitario"].between(90,200)]
df_filtrado

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130.0,0.00
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130.0,0.10
13,2024-01-05,Norte,Sofia Leon,Auriculares,Accesorios,11,130.0,0.00
14,2024-01-05,Sur,Pedro Diaz,Teclado Mec,Accesorios,12,95.0,0.05
18,2024-01-06,Oeste,Carlos Vega,Auriculares,Accesorios,2,130.0,0.10
...,...,...,...,...,...,...,...,...
1173,2024-12-22,Norte,Marta Ruiz,Teclado Mec,Accesorios,12,95.0,0.05
1177,2024-12-24,Oeste,Ana Torres,Auriculares,Accesorios,11,130.0,0.00
1183,2024-12-26,Centro,Luis Gomez,Auriculares,Accesorios,6,130.0,0.00
1189,2024-12-29,Oeste,Javier Sanz,Auriculares,Accesorios,6,130.0,0.00
1192,2024-12-30,Sur,Javier Sanz,Teclado Mec,Accesorios,8,95.0,0.10

In [26]:
df_filtrado["precio_unitario"]

0       130.0
4       130.0
13      130.0
14       95.0
18      130.0
        ...
1173     95.0
1177    130.0
1183    130.0
1189    130.0
1192     95.0
Name: precio_unitario, Length: 291, dtype: float64

In [ ]:
# ¿Cuántas operaciones se hicieron en la region Centro?

##ventas["region"].value_counts()["Centro"]
##(ventas["region"] == "Centro").sum()
len(ventas[ventas["region"] == "Centro"])

272

In [31]:
# Muestra las ventas de Tecnología con mas de 10 unidades

ventas[(ventas["categoria"] == "Tecnologia") & (ventas["unidades"] >10)]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320.0,0.00
16,2024-01-06,Centro,Ana Torres,Laptop Pro,Tecnologia,13,1200.0,0.00
27,2024-01-09,Este,Carlos Vega,Laptop Pro,Tecnologia,12,1200.0,0.00
40,2024-01-14,Centro,Marta Ruiz,Laptop Pro,Tecnologia,12,1200.0,0.10
89,2024-01-31,Centro,Sofia Leon,Monitor 27,Tecnologia,12,320.0,0.00
...,...,...,...,...,...,...,...,...
1174,2024-12-22,Norte,NaN,Laptop Pro,Tecnologia,14,1200.0,0.00
1176,2024-12-23,Centro,Carlos Vega,Monitor 27,Tecnologia,11,320.0,0.00
1181,2024-12-25,Sur,Ana Torres,Tablet Air,Tecnologia,14,640.0,0.00
1188,2024-12-28,Este,Luis Gomez,Tablet Air,Tecnologia,13,640.0,0.00
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200.0,0.05

In [33]:
# ¿Que ventas tuvieron algun descuento (mayor que 0)?

ventas[ventas["descuento"] >0]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130.0,0.10
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200.0,0.10
10,2024-01-04,Norte,Sofia Leon,Monitor 27,Tecnologia,3,320.0,0.10
11,2024-01-04,Oeste,Pedro Diaz,Escritorio,Mobiliario,10,450.0,0.05
12,2024-01-04,Centro,Marta Ruiz,Tablet Air,Tecnologia,2,640.0,0.15
...,...,...,...,...,...,...,...,...
1187,2024-12-28,Este,Ana Torres,Raton Ergo,Accesorios,8,45.0,0.05
1190,2024-12-29,Centro,Luis Gomez,Laptop Pro,Tecnologia,1,1200.0,0.10
1192,2024-12-30,Sur,Javier Sanz,Teclado Mec,Accesorios,8,95.0,0.10
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200.0,0.05
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320.0,0.05

In [35]:
## Ventas de las regiones Norte o Sur del producto "Latop PRO"

ventas[(ventas["region"].isin(["Norte", "Sur"])) & (ventas["producto"] == "Laptop Pro")]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
33,2024-01-11,Sur,Javier Sanz,Laptop Pro,Tecnologia,5,1200.0,NaN
108,2024-02-04,Sur,Ana Torres,Laptop Pro,Tecnologia,6,1200.0,0.00
119,2024-02-08,Norte,Luis Gomez,Laptop Pro,Tecnologia,6,1200.0,0.10
129,2024-02-11,Norte,Ana Torres,Laptop Pro,Tecnologia,2,1200.0,0.05
139,2024-02-13,Sur,Elena Mora,Laptop Pro,Tecnologia,8,1200.0,0.00
...,...,...,...,...,...,...,...,...
1100,2024-12-02,Sur,Sofia Leon,Laptop Pro,Tecnologia,10,1200.0,0.00
1105,2024-12-03,Sur,Sofia Leon,Laptop Pro,Tecnologia,7,1200.0,0.00
1123,2024-12-08,Norte,Javier Sanz,Laptop Pro,Tecnologia,13,1200.0,0.00
1146,2024-12-15,Norte,Pedro Diaz,Laptop Pro,Tecnologia,1,1200.0,0.00
1174,2024-12-22,Norte,NaN,Laptop Pro,Tecnologia,14,1200.0,0.00

In [36]:
# Ventas con importe superior a 5.000 ordenados de mayor a menos

ventas["importe"] = ventas["unidades"] * ventas["precio_unitario"]

ventas[ ventas["importe"] > 5000].sort_values("importe", ascending=False)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento,importe
340,2024-04-16,Este,Marta Ruiz,Laptop Pro,Tecnologia,14,1200.0,0.15,16800.0
344,2024-04-18,Norte,Luis Gomez,Laptop Pro,Tecnologia,14,1200.0,0.00,16800.0
1174,2024-12-22,Norte,NaN,Laptop Pro,Tecnologia,14,1200.0,0.00,16800.0
952,2024-10-17,Sur,Luis Gomez,Laptop Pro,Tecnologia,14,1200.0,0.10,16800.0
871,2024-09-25,Sur,Luis Gomez,Laptop Pro,Tecnologia,14,1200.0,0.05,16800.0
...,...,...,...,...,...,...,...,...,...
1065,2024-11-20,Este,Elena Mora,Tablet Air,Tecnologia,8,640.0,0.05,5120.0
1045,2024-11-09,Norte,Ana Torres,Tablet Air,Tecnologia,8,640.0,0.15,5120.0
1083,2024-11-27,Sur,Sofia Leon,Tablet Air,Tecnologia,8,640.0,0.00,5120.0
1053,2024-11-13,Centro,Ana Torres,Tablet Air,Tecnologia,8,640.0,0.05,5120.0
1162,2024-12-19,Oeste,Marta Ruiz,Tablet Air,Tecnologia,8,640.0,0.00,5120.0

In [ ]:
# Repite la consulta 4 usando query() y comprueba que da lo mismo
# Ventas de las regiones Norte o Sur d"el producto "Laptop Pro"
# ventas.query("region in ["Norte", "Sur"]" and producto == "Laptop Pro")

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2346129330.py, line 3)