In [1]:
import pandas as pd
print(pd.__version__)

3.0.5

In [3]:
s = pd.Series([120, 85, 200,45],
            index=["ene", "feb","mar", "abr"],
            name="ventas")

print(s["abr"])

45

In [4]:
print(s["mar"])

200

In [5]:
print(s*1.21)

ene    145.20
feb    102.85
mar    242.00
abr     54.45
Name: ventas, dtype: float64

In [7]:
s.mean()

np.float64(112.5)

In [8]:
s.max()

np.int64(200)

In [6]:
print(s.mean(), s.max())

112.5 200

DATAFRAME

In [9]:
import numpy as np

In [10]:
# a) Desde un diccionario de listas (la más habitual)
df = pd.DataFrame(
    {
        "producto": ["Laptop", "Monitor", "Teclado"],
        "unidades": [3, 7, 12],
        "precio":   [1200.0, 320.0, 95.0],
    }
)
print(df)

  producto  unidades  precio
0   Laptop         3  1200.0
1  Monitor         7   320.0
2  Teclado        12    95.0

In [11]:
df.head()

  producto  unidades  precio
0   Laptop         3  1200.0
1  Monitor         7   320.0
2  Teclado        12    95.0

In [12]:
# b) Desde una lista de diccionarios (típico de una API JSON)
df2 = pd.DataFrame([{"producto": "Laptop", "unidades": 3},
                    {"producto": "Monitor", "unidades": 7}])
df2.head()

  producto  unidades
0   Laptop         3
1  Monitor         7

In [14]:
# c) Desde una lista de listas, indicando las columnas
df3 = pd.DataFrame(
    [
        ["Laptop", 3], 
        ["Monitor", 7]
    ],
    columns=["producto", "unidades"]
)
df3.head()

  producto  unidades
0   Laptop         3
1  Monitor         7

In [15]:
# d) Desde un array de NumPy
df4 = pd.DataFrame(np.random.rand(3, 2), columns=["x", "y"])
df4.head()

          x         y
0  0.037667  0.647997
1  0.045888  0.998231
2  0.628947  0.929889

In [25]:
##Tu primer DataFrame

##Trabajas en una tienda y quieres pasar el inventario del papel al código.

# 1. Crea una Series con las temperaturas [21, 24, 19, 27, 30] e índice de lunes a 
# viernes.
temperaturas = pd.Series(
    [21,24,19,27,30],
    index=["Lunes", "Martes", "Miercoles", "Jueves", "Viernes"]
)
print(temperaturas)
# 2. Muestra la media, el máximo y el día que corresponde al máximo (usa .idxmax()).
print("="*100)
print("Media: ",temperaturas.mean())
print("Maximo: ", temperaturas.max())
print("Dia maximo:", temperaturas.idxmax())
print("Dia maximo indice: ", temperaturas.argmax())

# 3. Crea un DataFrame con 5 productos: nombre, categoría, stock y precio 
# (inventados).
print("="*100)
df = pd.DataFrame(
    {
        "nombre": ["Laptop", "Monitor", "Teclado", "Mouse", "Fuente de poder"],
        "categoria": ["Tecnologia", "Tecnologia", "Tecnologia", "Tecnologia", "Tecnologia"],
        "stock": [3, 7, 12, 1, 0],
        "precio":   [1200.0, 320.0, 95.0, 12.23, 90.8],
    }
)
df.head
# 4. Añade una columna valor_stock = stock × precio.
df["valor_stock"] = df["stock"] * df["precio"]
df.head()
# 5. Imprime la forma del DataFrame y la lista de nombres de columna
print(df.shape)
print(df.columns.to_list())

Lunes        21
Martes       24
Miercoles    19
Jueves       27
Viernes      30
dtype: int64
====================================================================================================
Media:  24.2
Maximo:  30
Dia maximo: Viernes
Dia maximo indice:  4
====================================================================================================
(5, 5)
['nombre', 'categoria', 'stock', 'precio', 'valor_stock']

##READ CSV

In [3]:
df = pd.read_csv("../data/ventas.csv")
df.head(n=10)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.1
5,2024-01-03,Oeste,Javier Sanz,Escritorio,Mobiliario,2,450,0.0
6,2024-01-03,Norte,Carlos Vega,Silla Ergo,Mobiliario,4,280,0.0
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280,0.0
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.1
9,2024-01-03,Centro,Pedro Diaz,Escritorio,Mobiliario,2,450,0.0

In [5]:
df.tail(5)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45,0.00

In [6]:
df.shape

(1200, 8)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   fecha            1200 non-null   str
 1   region           1200 non-null   str
 2   vendedor         1182 non-null   str
 3   producto         1200 non-null   str
 4   categoria        1200 non-null   str
 5   unidades         1200 non-null   int64
 6   precio_unitario  1200 non-null   int64
 7   descuento        1165 non-null   float64
dtypes: float64(1), int64(2), str(5)
memory usage: 75.1 KB

In [8]:
df.describe()

          unidades  precio_unitario    descuento
count  1200.000000      1200.000000  1165.000000
mean      7.275833       387.412500     0.047639
std       4.054024       346.020316     0.056273
min       1.000000        45.000000     0.000000
25%       4.000000       130.000000     0.000000
50%       7.000000       280.000000     0.000000
75%      11.000000       450.000000     0.100000
max      14.000000      1200.000000     0.150000

In [9]:
df["unidades"].max()

np.int64(14)

In [11]:
df.sample(10)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
767,2024-08-23,Sur,Carlos Vega,Raton Ergo,Accesorios,11,45,0.05
836,2024-09-14,Sur,Sofia Leon,Escritorio,Mobiliario,10,450,0.00
113,2024-02-05,Sur,Ana Torres,Escritorio,Mobiliario,7,450,0.05
872,2024-09-25,Norte,Marta Ruiz,Raton Ergo,Accesorios,1,45,0.00
330,2024-04-13,Oeste,Carlos Vega,Teclado Mec,Accesorios,8,95,0.00
443,2024-05-21,Oeste,Elena Mora,Silla Ergo,Mobiliario,7,280,0.00
634,2024-07-14,Norte,Luis Gomez,Raton Ergo,Accesorios,12,45,0.15
1109,2024-12-04,Centro,Sofia Leon,Escritorio,Mobiliario,13,450,0.15
351,2024-04-20,Centro,Carlos Vega,Auriculares,Accesorios,12,130,0.00
480,2024-06-04,Centro,Marta Ruiz,Silla Ergo,Mobiliario,8,280,0.00

In [12]:
df.describe(include="object")

C:\Users\Intel\AppData\Local\Temp\ipykernel_760\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

             fecha region    vendedor    producto   categoria
count         1200   1200        1182        1200        1200
unique         349      5           8           8           3
top     2024-02-21  Norte  Marta Ruiz  Silla Ergo  Tecnologia
freq             9    305         170         177         447

In [13]:
df["region"].unique()

<StringArray>
['Oeste', 'Sur', 'Centro', 'Norte', 'Este']
Length: 5, dtype: str

In [14]:
df["region"].nunique()

5

In [16]:
df["region"].value_counts()

region
Norte     305
Centro    272
Sur       240
Oeste     203
Este      180
Name: count, dtype: int64

In [22]:
df["producto"]

0       Auriculares
1        Monitor 27
2        Silla Ergo
3        Laptop Pro
4       Auriculares
           ...
1195     Raton Ergo
1196     Laptop Pro
1197     Monitor 27
1198     Monitor 27
1199     Raton Ergo
Name: producto, Length: 1200, dtype: str

In [20]:
df["producto"].mode()

0    Silla Ergo
Name: producto, dtype: str

### SELECCIONAR COLUMNAS

In [24]:
df["producto"]

0       Auriculares
1        Monitor 27
2        Silla Ergo
3        Laptop Pro
4       Auriculares
           ...
1195     Raton Ergo
1196     Laptop Pro
1197     Monitor 27
1198     Monitor 27
1199     Raton Ergo
Name: producto, Length: 1200, dtype: str

In [23]:
df[["fecha", "region", "unidades"]]

           fecha  region  unidades
0     2024-01-02   Oeste         5
1     2024-01-02     Sur        14
2     2024-01-02  Centro         1
3     2024-01-02  Centro        10
4     2024-01-03     Sur         2
...          ...     ...       ...
1195  2024-12-30    Este         4
1196  2024-12-30    Este        13
1197  2024-12-31   Oeste         2
1198  2024-12-31   Norte         6
1199  2024-12-31   Norte         8

[1200 rows x 3 columns]

In [26]:
df.head(2)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0

In [25]:
df.loc[0]

fecha               2024-01-02
region                   Oeste
vendedor            Pedro Diaz
producto           Auriculares
categoria           Accesorios
unidades                     5
precio_unitario            130
descuento                  0.0
Name: 0, dtype: object

In [27]:
df.loc[0:2, ["producto","unidades"]]

      producto  unidades
0  Auriculares         5
1   Monitor 27        14
2   Silla Ergo         1

In [28]:
df.loc[:, ["producto", "unidades"]]

         producto  unidades
0     Auriculares         5
1      Monitor 27        14
2      Silla Ergo         1
3      Laptop Pro        10
4     Auriculares         2
...           ...       ...
1195   Raton Ergo         4
1196   Laptop Pro        13
1197   Monitor 27         2
1198   Monitor 27         6
1199   Raton Ergo         8

[1200 rows x 2 columns]

In [29]:
df.tail()

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45,0.00

In [31]:
df.iloc[-1]

fecha              2024-12-31
region                  Norte
vendedor           Marta Ruiz
producto           Raton Ergo
categoria          Accesorios
unidades                    8
precio_unitario            45
descuento                 0.0
Name: 1199, dtype: object

In [32]:
df.iloc[-5:,1]

1195     Este
1196     Este
1197    Oeste
1198    Norte
1199    Norte
Name: region, dtype: str

In [33]:
df.iloc[-5:, 3:6]

        producto   categoria  unidades
1195  Raton Ergo  Accesorios         4
1196  Laptop Pro  Tecnologia        13
1197  Monitor 27  Tecnologia         2
1198  Monitor 27  Tecnologia         6
1199  Raton Ergo  Accesorios         8

In [36]:
df.sort_values(["region","unidades"], ascending=[True,False])

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
76,2024-01-27,Centro,Javier Sanz,Escritorio,Mobiliario,14,450,0.00
83,2024-01-30,Centro,Elena Mora,Auriculares,Accesorios,14,130,0.10
162,2024-02-19,Centro,Elena Mora,Monitor 27,Tecnologia,14,320,0.15
391,2024-04-30,Centro,Carlos Vega,Silla Ergo,Mobiliario,14,280,0.00
446,2024-05-23,Centro,Luis Gomez,Raton Ergo,Accesorios,14,45,0.05
...,...,...,...,...,...,...,...,...
1044,2024-11-09,Sur,Sofia Leon,Teclado Mec,Accesorios,1,95,0.10
1079,2024-11-26,Sur,Elena Mora,Tablet Air,Tecnologia,1,640,0.15
1094,2024-12-01,Sur,Marta Ruiz,Silla Ergo,Mobiliario,1,280,0.00
1104,2024-12-03,Sur,Pedro Diaz,Monitor 27,Tecnologia,1,320,0.05
1126,2024-12-08,Sur,Pedro Diaz,Escritorio,Mobiliario,1,450,0.00

In [37]:
df.sort_values("unidades", ascending=False).iloc[:5,:]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
420,2024-05-14,Este,Javier Sanz,Monitor 27,Tecnologia,14,320,0.10
309,2024-04-07,Norte,Elena Mora,Tablet Air,Tecnologia,14,640,0.05
607,2024-07-07,Centro,Javier Sanz,Auriculares,Accesorios,14,130,0.05
604,2024-07-05,Sur,Elena Mora,Laptop Pro,Tecnologia,14,1200,0.00
601,2024-07-05,Sur,Pedro Diaz,Monitor 27,Tecnologia,14,320,0.05

In [39]:
df.sort_values("unidades", ascending=False)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
420,2024-05-14,Este,Javier Sanz,Monitor 27,Tecnologia,14,320,0.10
309,2024-04-07,Norte,Elena Mora,Tablet Air,Tecnologia,14,640,0.05
607,2024-07-07,Centro,Javier Sanz,Auriculares,Accesorios,14,130,0.05
604,2024-07-05,Sur,Elena Mora,Laptop Pro,Tecnologia,14,1200,0.00
601,2024-07-05,Sur,Pedro Diaz,Monitor 27,Tecnologia,14,320,0.05
...,...,...,...,...,...,...,...,...
447,2024-05-23,Oeste,Marta Ruiz,Silla Ergo,Mobiliario,1,280,0.00
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280,0.00
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.10
407,2024-05-06,Este,Elena Mora,Laptop Pro,Tecnologia,1,1200,0.05
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00

In [41]:
df.nlargest(5, ["unidades", "precio_unitario"])

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
340,2024-04-16,Este,Marta Ruiz,Laptop Pro,Tecnologia,14,1200,0.15
344,2024-04-18,Norte,Luis Gomez,Laptop Pro,Tecnologia,14,1200,0.00
604,2024-07-05,Sur,Elena Mora,Laptop Pro,Tecnologia,14,1200,0.00
871,2024-09-25,Sur,Luis Gomez,Laptop Pro,Tecnologia,14,1200,0.05
952,2024-10-17,Sur,Luis Gomez,Laptop Pro,Tecnologia,14,1200,0.10

In [42]:
df.nsmallest(5,["unidades", "precio_unitario"])

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
224,2024-03-05,Centro,Ana Torres,Raton Ergo,Accesorios,1,45,NaN
248,2024-03-13,Centro,Javier Sanz,Raton Ergo,Accesorios,1,45,0.00
249,2024-03-14,Este,Sofia Leon,Raton Ergo,Accesorios,1,45,0.00
260,2024-03-19,Norte,Marta Ruiz,Raton Ergo,Accesorios,1,45,0.00
276,2024-03-27,Norte,Marta Ruiz,Raton Ergo,Accesorios,1,45,0.05